'use strict'

// Known malicious packages sourced from npm security advisories,
// GitHub Security Advisories, and public threat intelligence reports.
const BLOCKLIST = new Set([
  // Compromised/backdoored packages
  'event-stream',
  'flatmap-stream',
  'node-ipc',
  'ua-parser-js',
  'coa',
  'rc',
  'colors',
  'faker',

  // Typosquatting - targeting popular packages
  'crossenv',
  'cross-env.js',
  'ffmmpeg',
  'babelcli',
  'nodecaffe',
  'nodefabric',
  'node-fabric',
  'nodeffmpeg',
  'nodemysql',
  'node-opencv',
  'node-openssl',
  'node-os',
  'node-paint',
  'node-pentest',
  'node-sqlite',
  'node-tkinter',
  'nodecrypto',
  'nodeftp',
  'nodemailer-js',
  'nodemailer.js',
  'socketio',
  'socket.io.js',
  'discordie',
  'mongose',
  'mssql-node',
  'mysqljs',
  'node-sass-middleware',
  'gruntcli',
  'jquey',
  'jquery.js',
  'd3.js',
  'require',
  'loadash',
  'momnet',
  'expres',
  'expresss',
  'reakt',
  'reactt',
  'vue.js',
  'vuejs',
  'angularjs',
  'lodahs',
  'lodash.js',
  'requets',
  'requset',
  'underscore.js',
  'underscorejs',
  'webpak',
  'webpackk',
  'axio',
  'axxios',
  'dotenv.js',

  // Known credential stealers (public reports)
  'electron-native-notify',
  'getcookies',
  'http-fetch-client',
  'aws-sdk-config',
  'node-browserify',
  'nodecookies',
  'xss-payloads',
])

module.exports = { BLOCKLIST }
